#!/usr/bin/env python3
import subprocess
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_MODULE_DIR = _PROGRAM_DIR / "src" / "gazetteer_matcher"
_TESTS_DIR = _PROGRAM_DIR / "tests"

_FORMAT_DIRS = [_MODULE_DIR, _TESTS_DIR]

python_exe = "python3"
subprocess.check_call([python_exe, "-m", "black"] + _FORMAT_DIRS)
subprocess.check_call([python_exe, "-m", "isort"] + _FORMAT_DIRS)
