#!/usr/bin/env python3
import subprocess
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_MODULE_DIR = _PROGRAM_DIR / "src" / "gazetteer_matcher"
_TESTS_DIR = _PROGRAM_DIR / "tests"

_LINT_DIRS = [_MODULE_DIR, _TESTS_DIR]

python_exe = "python3"
subprocess.check_call([python_exe, "-m", "black"] + _LINT_DIRS + ["--check"])
subprocess.check_call([python_exe, "-m", "isort"] + _LINT_DIRS + ["--check"])
subprocess.check_call([python_exe, "-m", "flake8"] + _LINT_DIRS)
subprocess.check_call([python_exe, "-m", "pylint"] + _LINT_DIRS)
subprocess.check_call([python_exe, "-m", "mypy"] + _LINT_DIRS)
