#!/usr/bin/env python3
import subprocess
import sys
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_TEST_DIR = _PROGRAM_DIR / "tests"

python_exe = "python3"
subprocess.check_call([python_exe, "-m", "pytest", _TEST_DIR] + sys.argv[1:])
